### ISSUE TITLE
starting tomcat-georchestra failed

### ISSUE THREAD

**Issue by fvanderbiest** [landryb/georchestra-ansible#3]
```
TASK: [tomcat | start instance] *********************************************** 
changed: [default] => (item=proxycas)
failed: [default] => (item=georchestra) => {"failed": true, "item": "georchestra"}
msg: Starting Tomcat servlet engine: tomcat-georchestra failed!

failed: [default] => (item=geoserver) => {"failed": true, "item": "geoserver"}
msg: Starting Tomcat servlet engine: tomcat-geoserver failed!
```

**Comment by landryb** [comment]
Well, having a look at the corresponding catalina.out logs would help...

**Comment by fvanderbiest** [comment]
Sure, I did not have time to go further yesterday night ...
```
SEVERE: Failed to open access log file [/srv/log/access-proxycas.2015-01-27.txt]
java.io.FileNotFoundException: /srv/log/access-proxycas.2015-01-27.txt (No such file or directory)
	at java.io.FileOutputStream.openAppend(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:210)
	at org.apache.catalina.valves.AccessLogValve.open(AccessLogValve.java:816)
	at org.apache.catalina.valves.AccessLogValve.start(AccessLogValve.java:942)
	at org.apache.catalina.core.StandardPipeline.start(StandardPipeline.java:233)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1062)
	at org.apache.catalina.core.StandardHost.start(StandardHost.java:840)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1057)
	at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
	at org.apache.catalina.core.StandardService.start(StandardService.java:525)
	at org.apache.catalina.core.StandardServer.start(StandardServer.java:754)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:595)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
```
same with /srv/log/access-georchestra.2015-01-27.txt & /srv/log/access-geoserver.2015-01-27.txt
